Added method to refresh skills page and passed as prop to modal
maryvilledev/skilldirectoryui pull request #33
Opened 2017-01-12 20:49 UTC by dane-johnson

2017-01-12 20:55 UTC, thebho requested changes

2017-01-12 20:55 UTC, thebho commented on src/Skills.jsx
> +  reloadSkills() {
If this has the same functionality as componentDidMount(), you should have that method call this too.  No reason to call the same axios.get() in 2 different places

2017-01-12 21:31 UTC, solkaz commented
Other than Brian's requested changes, this looks good to me, and it implements most of the changes I had made. I had gone further and refactored SkillForm to use a single callback to Skills to handle getting the new skill's name and type and closing the modal, but I can implement those changes on top of this PR

2017-01-13 20:11 UTC, dane-johnson reviewed
This all LGTM but I think the purpose of this issue was really just to fix the not refreshing bug, whereas this seems like a major refactor of the skills file. I do think that is something we need, but I don't know if that should really be done here.

2017-01-16 21:15 UTC, Hopding approved these changes
Nice 👍

2017-01-17 19:54 UTC, dane-johnson commented
I think this is good to go

2017-01-17 23:17 UTC, thebho approved these changes

2017-01-17 23:18 UTC, thebho commented
Looks good, will merge in morning

2017-01-18 14:30 UTC, merged